### PR TITLE
Fixed main menu display issues. 

### LINKED ISSUE #48: Bug: Main Menu Display Issues
* When the application can't clear the console display with the error displayed: "sh: cls: command not found"
* Fix the mis-formatting issue of  "invalid choice display" - 
Invalid choice display error

### PR DESCRIPTION
**Pull request by MiaYWei**
*When the application can't clear the console display with the error displayed: "sh: cls: command not found"
*Fix the mis-formatting issue of "invalid choice display"
Invalid choice display error

### CODE REVIEW

**Review by krithigasr — APPROVED** [review]

File: src/menu_display.c [hunk 1]
```diff
@@ -53,44 +53,51 @@ void display_rules(void)
...
+    // printf(" Win the Game\n");
     printf("  Once a player has no cards left, the game is over. The player who exhausts all of his cards quickly is the winner of the game.\n");
     printf("  If no player is out of cards by the time the DRAW pile is depleted, the DISCARD pile is reshuffled and set as the draw pile. \n\n");
     printf("************************************************************************\n\n");
 
-     printf(" Inputs to play the game\n");
+    printf(" Inputs to play the game\n");
     printf("  To request a card from the Draw pile, Press N or n. \n");
     printf("  To end turn, Press E or e. \n");
     printf("  To discard a card - Say you want discard(RED,3), Press R3.\n");
```
Comment (krithigasr) [inline src/menu_display.c]: can you add " Say you want **to** discard" here?

Comment (MiaYWei) [reply src/menu_display.c]: Updated.

**Review by krithigasr — APPROVED** [review]

**Review by aditibhardwaj98 — APPROVED** [review]

**Review by HongBo713 — APPROVED** [review]
